### ISSUE TITLE
Fix RTD docs

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/mmcif_pdbx#54]
Badge status shows docs failing for 2eab2a5

**Comment by intendo** [comment]
@sobolevnrm:
This is a nightmare to get all the supporting tools to find the current version number from a single location.

The reason for the current failed build is that readthedocs does not run `pip install -e .` to install the current `mmcif_pdbx` before the build so the `docs/conf.py` cannot import `pdbx` during the build.

According to [readthedocs config-file](https://docs.readthedocs.io/en/stable/config-file/v2.html#python),  we could add a `.readthedocs.yaml` at the top level directory and a `docs/requirements.txt` file to specify the sphinx configuration. 

I think the `.readthedocs.yaml` file would look like:

```
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
   version: stable
   install:
     - method: pip
       path: .
```

We could move the `sphinx_rtd_theme` entry from `requirements.txt` to `docs/requirements.txt`. This makes the install for the normal user need fewer requirements and more correct (separation of concerns).

So `requirements.txt` would contain:
```
pytest==5.4.3
```
And `docs/requirements.txt` which is only needed for `readthedocs` would contain:
```
sphinx_rtd_theme==0.5.0
```
